### ISSUE TITLE
Deleting a File Reference Keeps Depot File

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.file#1]
Deleting the file reference seems not to delete the corresponding file in the depot.

**Comment by href** [comment]
Fixed in 73191d941a5. I'd be happy if you could test this with the events import on your side. I think it shouldn't cause any issues but I think it makes sense to have this run locally for a bit first before pushing a new release.

**Comment by href** [comment]
This has been fixed upstream. Once a new `filedepot` release is out, we can remove our custom event handler (but leave the tests).

**Comment by msom** [comment]
👍🏻

The patch looks good with onegov.events but the problem seems to persist with one-on-one relations (e.g. in onegov.agency). I will test it again with the new filedepot releasen.

**Comment by href** [comment]
Okay, if it persists can you add a test to onegov.file that demonstrates the issue?

**Comment by msom** [comment]
Done

**Comment by href** [comment]
I don't see a transaction.commit in this test. That is however required - if the file was deleted during session.flush, one could not abort the transaction safely. Am I missing something?

**Comment by msom** [comment]
You're right, of course. Adding transaction.commit doesn't make any difference, though (see updated test).

**Comment by href** [comment]
The test passes for me with the latest filedepot master:
`pip install --force git+https://github.com/amol-/depot\?#egg=filedepot`

It does not work with our work-around though.

**Comment by msom** [comment]
👍🏻
